# Generated by Django 5.2.12 on 2026-04-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hex', models.CharField(max_length=500, unique=True)),
                ('dedo', models.CharField(choices=[('polegar_d', 'Polegar Direito'), ('indicador_d', 'Indicador Direito'), ('polegar_e', 'Polegar Esquerdo'), ('indicador_e', 'Indicador Esquerdo'), ('outro', 'Outro')], default='polegar_d', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitais', to='students.estudante')),
            ],
        ),
    ]
