# Generated by Django 5.2.12 on 2026-06-14 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoValidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_refeicoes', models.IntegerField()),
                ('valor_por_refeicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiscal_email', models.EmailField(max_length=254)),
                ('protocolo', models.CharField(max_length=50, unique=True)),
                ('data_validacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('pode_ser_alterado', models.BooleanField(default=False)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogPeriodoValidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.periodovalidado')),
            ],
        ),
    ]
