# Generated by Django 5.2.12 on 2026-06-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodovalidado',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
