# Generated by Django 5.2.12 on 2026-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoco',
            name='metodo',
            field=models.CharField(choices=[('biometria', 'Biometria'), ('manual', 'Manual')], max_length=20),
        ),
    ]
