# Generated by Django 5.2.12 on 2026-05-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_almoco_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoco',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
